[package]
edition = "2024"
name = "derive_fromstr"
version = "0.1.0"
description = "derive fromstr for some enums"
license = "MIT"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true

